import { createRequire } from "node:module";
import { readFileSync } from "node:fs";
import { strict as assert } from "node:assert";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { prepareSection, sectionToCourse } from "../src/lib/ajou-catalog.ts";
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.AJOU_PLAYWRIGHT_MODULE || "playwright");
const catalog = JSON.parse(readFileSync(new URL("../src/data/ajou-2026-2.json", import.meta.url), "utf8"));
const courses = ["X024", "F126"].map((id) => sectionToCourse(prepareSection(catalog.courses.find((s) => s.registrationNumber === id)), "#2563eb"));
const browser = await chromium.launch({ channel: "msedge", headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
const page = await context.newPage();
const errors = [];
page.on("pageerror", (e) => errors.push(e.message));
const base = process.env.AJOU_TEST_URL || "http://127.0.0.1:3000";
try {
  await page.goto(base + "/community", { waitUntil: "domcontentloaded" });
  await page.getByRole("heading", { name: "같은 과목, 같은 분반과 함께" }).waitFor();
  await page.getByRole("button", { name: "내 수업 0", exact: true }).waitFor();
  await page.evaluate((items) => {
    localStorage.setItem("unilink:courses", JSON.stringify(items));
    localStorage.setItem("unilink:posts", JSON.stringify([{ id: "old-general", title: "이전 일반 글", content: "보존", category: "자유", authorId: "old", authorName: "익명", isAnonymous: true, likes: 0, commentCount: 0, createdAt: "2026-09-01T00:00:00Z" }]));
    window.dispatchEvent(new Event("storage"));
  }, courses);
  await page.getByRole("button", { name: "내 수업 2", exact: true }).waitFor();
  assert.equal(await page.getByRole("heading", { name: "이전 일반 글", exact: true }).count(), 0);
  await page.goto(base + "/community?courseId=" + courses[0].id);
  await page.getByRole("heading", { name: courses[0].name, exact: true }).waitFor();
  await page.waitForFunction(() => document.querySelector('[aria-label="분반 필터"]')?.value === "X024");
  await page.getByRole("button", { name: "글쓰기", exact: true }).click();
  let dialog = page.getByRole("dialog");
  assert.equal(await dialog.getByRole("combobox", { name: "작성 분반" }).inputValue(), "X024");
  await dialog.getByRole("textbox", { name: "글 제목" }).fill("X024 분반 과제 질문");
  await dialog.getByRole("textbox", { name: "글 내용" }).fill("이번 주 과제 범위를 확인하고 싶어요.");
  await dialog.getByRole("button", { name: "게시하기", exact: true }).click();
  await page.getByRole("heading", { name: "X024 분반 과제 질문", exact: true }).waitFor();
  await page.getByRole("combobox", { name: "분반 필터", exact: true }).selectOption("X025");
  await page.getByRole("heading", { name: "X024 분반 과제 질문", exact: true }).waitFor({ state: "hidden" });
  await page.getByRole("button", { name: "글쓰기", exact: true }).click();
  dialog = page.getByRole("dialog");
  await dialog.getByRole("combobox", { name: "작성 분반" }).selectOption("");
  await dialog.getByRole("textbox", { name: "글 제목" }).fill("모든 분반 공통 자료");
  await dialog.getByRole("textbox", { name: "글 내용" }).fill("공통 자료 안내입니다.");
  await dialog.getByRole("button", { name: "게시하기", exact: true }).click();
  await page.getByRole("heading", { name: "모든 분반 공통 자료", exact: true }).waitFor();
  await page.getByRole("combobox", { name: "분반 필터", exact: true }).selectOption("X025");
  const common = page.locator("article").filter({ has: page.getByRole("heading", { name: "모든 분반 공통 자료", exact: true }) });
  await common.getByRole("button", { name: "좋아요 0", exact: true }).click();
  await common.getByRole("button", { name: "댓글 0", exact: true }).click();
  await common.getByRole("textbox", { name: "댓글 내용" }).fill("감사합니다!");
  await common.getByRole("button", { name: "댓글 등록", exact: true }).click();
  await common.getByText("감사합니다!", { exact: true }).waitFor();
  await page.reload();
  await page.getByRole("heading", { name: "모든 분반 공통 자료", exact: true }).waitFor();
  assert.equal(await common.getByRole("button", { name: "좋아요 1", exact: true }).getAttribute("aria-pressed"), "true");
  await common.getByRole("button", { name: "댓글 1", exact: true }).click();
  await common.getByText("감사합니다!", { exact: true }).waitFor();
  await page.screenshot({ path: join(tmpdir(), "community-desktop.png"), fullPage: true });

  // Same-route URL navigation must react without a document reload.
  await page.evaluate((id) => history.pushState(null, "", "?courseId=" + id), courses[1].id);
  await page.getByRole("heading", { name: courses[1].name, exact: true }).waitFor();
  assert.equal(await page.getByRole("heading", { name: "모든 분반 공통 자료", exact: true }).count(), 0);

  const peer = await context.newPage();
  await peer.goto(base + "/community");
  await peer.evaluate((id) => localStorage.setItem("unilink:courses", JSON.stringify(JSON.parse(localStorage.getItem("unilink:courses")).filter((c) => c.id !== id))), courses[0].id);
  await page.getByRole("button", { name: "내 수업 1", exact: true }).waitFor();
  await page.getByRole("button", { name: "개설 과목 탐색", exact: true }).click();
  await page.getByRole("textbox", { name: "수업 게시판 검색" }).fill("X024");
  await page.getByRole("button", { name: "게시판 " + courses[0].name + " " + courses[0].courseCode, exact: true }).click();
  await page.getByRole("heading", { name: "모든 분반 공통 자료", exact: true }).waitFor();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole("button", { name: "글쓰기", exact: true }).click();
  dialog = page.getByRole("dialog");
  await dialog.getByRole("textbox", { name: "글 제목" }).fill("모바일 확인");
  await dialog.getByRole("textbox", { name: "글 내용" }).fill("모바일에서도 글을 작성할 수 있습니다.");
  await page.screenshot({ path: join(tmpdir(), "community-mobile.png"), fullPage: true });
  const bounds = await dialog.boundingBox();
  assert.ok(bounds.x >= 0 && bounds.x + bounds.width <= 391);
  await dialog.getByRole("button", { name: "게시하기", exact: true }).click();
  await page.getByRole("heading", { name: "모바일 확인", exact: true }).waitFor();
  assert.ok(await page.evaluate(() => JSON.parse(localStorage.getItem("unilink:community-v2")).posts.some((p) => p.id === "old-general")));
  assert.deepEqual(errors, []);
  console.log("PASS: timetable auto-link, course/section isolation, common posts, publishing, comments, likes/reload, deep links, cross-tab changes, removal preservation, mobile, legacy preservation.");
} catch (error) {
  await page.screenshot({ path: join(tmpdir(), "community-error.png"), fullPage: true });
  throw error;
} finally { await context.close(); await browser.close(); }
